config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'
  get 'chats/show'
  resources :messages
  devise_for :users
  get '/chat/:name' => 'messages#chat', as: 'chat'
  get '/chats' => 'messages#chats', as: 'chats'

  post '/sessions', to: 'sessions#create'
  mount ActionCable.server, at: '/cable'

 # The priors
  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     endig
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root 'messages#chats'


end

app/models/message.rb
class Message < ApplicationRecord

  include ::ActionView::Helpers::TextHelper
  has_rich_text :content

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    if @message.save
      ActionCable.server.broadcast 'room_channel', msg_time: Time.now, recipients: @message.recipients, sender: @message.sender, sender_name: User.find(@message.sender).name, content: @message.content
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  def chats
   @chats=Message.where("recipients = ?", current_user.id).group(:sender)
  end
  
  def chat
    @message=Message.new
      if User.find_by(name: params[:name])
		@conversation_with=User.find_by(name: params[:name])
		@messages=Message.where("recipients=#{@conversation_with.id} and sender=#{current_user.id} OR recipients=#{current_user.id} and sender=#{@conversation_with.id}").order(:created_at)
        Message.where("recipients=? and sender=? and read_at is null", current_user.id, @conversation_with.id ).update_all(read_at: Time.now)
        cookies[:current_user_id] = current_user.id      
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender, :recipients, :content, :read_at, :name)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sender %>
    <%= form.number_field :sender %>
  </div>

  <div class="field">
    <%= form.label :recipients %>
    <%= form.number_field :recipients %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/chat.html.erb
<h3>Conversation with <%= @conversation_with.name %></h3>
<div id="message_holder">
   <% @messages.each do |m| %>
		<% if m.sender==@conversation_with.id %>
			<div class="container-left">
				<div class="subscript"><%= User.find(m.sender).name %><br><%= I18n.l m.created_at %></div>
				<%= m.content %>
			</div>
	    <% else %>
			<div class="container-right">
				<div class="subscript"><%= User.find(m.sender).name %><br><%= I18n.l m.created_at %></div>
				<%= m.content %>
            </div>
		<% end %>
	<% end %>
</div>

<%= form_with model: @message, multipart: true, remote: true do |f| %>
    <%= f.rich_text_area :content, class: 'form-control' %>
    <%= f.hidden_field :recipients, value: @conversation_with.id %>
    <%= f.hidden_field :sender, value: current_user.id %>
    <%= f.submit 'Send' %>
<% end %>

app/views/messages/chats.html.erb
<h2>Chats</h2>
<br>
<div id="messages_holder">
<% @chats.each do |c| %>
 <% if Message.where("recipients=? and sender=? and read_at is null", current_user.id, User.find(c.sender).id).count > 0 %>
	<div><b>(<%= Message.where("recipients=? and sender=? and read_at is null", current_user.id, User.find(c.sender).id).count %>) <%= link_to User.find(c.sender).name, chat_path(name: User.find(c.sender).name) %></b></div>
 <% else %>
	<div><%= link_to User.find(c.sender).name, chat_path(name: User.find(c.sender).name) %></div>
 <% end %>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Recipients</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender %></td>
        <td><%= message.recipients %></td>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/messages.html.erb
<h3><%= (t 'messages_') %></h3>


<%= @conversation.subject %>
 
<%= @conversation.receipts_for current_user do |receipt| %>
 <% message = receipt.message %>
 <%= message.sender.name %>
 <%= simple_format h message.body %>
 <%= (t 'sent_') time_ago_in_words(message.updated_at)  (t 'ago_') %>
<% end %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/send_message.html.erb
<%= form_tag("/messages/send_message", method: "post", url: send_message_path) do  %>
<%= hidden_field_tag :user_id, "#{@user.id}" %>
<%= text_field_tag :subject, nil, :class => 'form-control', :placeholder => (t 'subject') %>
<%= text_area_tag :message, nil, :class => 'form-control', :placeholder => (t 'message_') %>
<%= submit_tag(value=(t 'submit_')), :class => "btn btn-primary " %>
<% end %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender %>
</p>

<p>
  <strong>Recipients:</strong>
  <%= @message.recipients %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>