config/routes.rb
Rails.application.routes.draw do

  get 'chats/index'
  get 'chats/show'
  resources :messages
  devise_for :users
  get '/chat/:name' => 'messages#chat', as: 'chat'
  get '/chats' => 'messages#chats', as: 'chats'

  post '/sessions', to: 'sessions#create'
  mount ActionCable.server, at: '/cable'

 # The priors
  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     endig
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  root 'messages#chats'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %></title>
<%= favicon_pack_tag 'favicon.ico' %>
<%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'   %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body class="<%= controller.controller_name %>">

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
	  
   
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
        </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		  <%= link_to (t 'messages_'), chats_path, class: "dropdown-item" %>
		  <%= link_to (t 'sign_out'),  destroy_user_session_path, class: "dropdown-item",  method: :delete %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to (t 'sign_in'), new_user_session_path %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

 <div id="columns" class="columns">

  <div id="side">
  </div>
  
  <div id="main">
     <%= yield %>
  </div>

 </div>

</body>
</html>